version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SERVER_ROOT_URL=https://${GRAFANA_DOMAIN}
      - GF_SERVER_DOMAIN=${GRAFANA_DOMAIN}
    networks:
      - apptelink-prueba-grafana-stmpjq
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana-web.rule=Host(`${GRAFANA_DOMAIN}`)
      - traefik.http.routers.grafana-web.entrypoints=web
      - traefik.http.routers)grafana-web.middlewares=redirect-to-https@file
      - traefik.http.services.grafana-web.loadbalancer.server.port=3000
      - traefik.http.routers.grafana-websecure.rule=Host(`${GRAFANA_DOMAIN}`)
      - traefik.http.routers.grafana-websecure.entrypoints=websecure
      - traefik.http.routers.grafana-websecure.tls=true
      - traefik.http.routers.grafana-websecure.tls.certresolver=letsencrypt
      - traefik.http.services.grafana-websecure.loadbalancer.server.port=3000

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - prometheus-storage:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - apptelink-prueba-grafana-stmpjq

  loki:
    image: grafana/loki:latest
    restart: unless-stopped
    volumes:
      - loki-storage:/loki
      - ./loki-config.yml:/etc/loki/loki-config.yml
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - apptelink-prueba-grafana-stmpjq

  tempo:
    image: grafana/tempo:latest
    restart: unless-stopped
    volumes:
      - tempo-storage:/tmp/tempo
      - ./tempo-config.yml:/etc/tempo/tempo-config.yml
    command: -config.file=/etc/tempo/tempo-config.yml
    networks:
      - apptelink-prueba-grafana-stmpjq

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    restart: unless-stopped
    volumes:
      - ./otel-collector-config.yml:/etc/otelcol-contrib/config.yaml
    command: --config=/etc/otelcol-contrib/config.yaml
    networks:
      - apptelink-prueba-grafana-stmpjq

volumes:
  grafana-storage: {}
  prometheus-storage: {}
  loki-storage: {}
  tempo-storage: {}

networks:
  apptelink-prueba-grafana-stmpjq:
    name: apptelink-prueba-grafana-stmpjq
    external: true